"""Manual schedule search inside the user's parameterisation (2026-09-13).

Parameters: b = where the T=0 stretch ends; T_end in [0.8, 1.0]; any number of
free control points between b and the end, anywhere in [0, 1]. Round 1 builds on
the current best, shape_b50_concave = [[0,0],[0.5,0],[0.75,0.75],[1,0.95]]
(MIND 0.0285, n=1): bend it higher, bend it earlier, end at exactly 1.0, and
move the blade end. Piecewise-linear control points, as in shape_search.py.

Usage: python manual_search.py [--dry-run]   # adds phase "manual" and phase "grid" entries to the manifest
"""
import os as _os
AMBIENT_BASE = _os.environ.get("AMBIENT_BASE") or next(
    (_p for _p in ("/data-local/honjar", "/var/local/honjar", "/data/scratch/honjar")
     if _os.path.isdir(_p)), "/data/scratch/honjar")
import argparse, json, os, shutil
MANIFEST = f"{AMBIENT_BASE}/generated/dyn_search_manifest.json"
PHASE = "manual"

def pw(points):
    return {"type": "piecewise", "control_points": [[float(a), float(b)] for a, b in points]}

ROUND1 = [
    ("man_b50_bend85",        "winner bent higher: 0.85 at 75%",               pw([(0,0),(0.5,0),(0.75,0.85),(1,0.95)])),
    ("man_b50_bend95",        "winner bent to the ceiling: 0.95 at 75%, flat after", pw([(0,0),(0.5,0),(0.75,0.95),(1,0.95)])),
    ("man_b50_bendearly",     "winner bent earlier: 0.75 at 62.5%",            pw([(0,0),(0.5,0),(0.625,0.75),(1,0.95)])),
    ("man_b50_concave_end100","winner ending at exactly 1.0",                   pw([(0,0),(0.5,0),(0.75,0.75),(1,1.0)])),
    ("man_b40_concave",       "winner shape with the blade ending at 40%",     pw([(0,0),(0.4,0),(0.7,0.75),(1,0.95)])),
    ("man_b60_concave",       "winner shape with the blade ending at 60%",     pw([(0,0),(0.6,0),(0.8,0.75),(1,0.95)])),
]
ROUND2 = [   # coverage round (2026-09-13): fill the empty cells of (blade end, T_end, middle shape)
    ("man_b75_linear",     "very late blade: T=0 until 75%, straight to 0.95",            pw([(0,0),(0.75,0),(1,0.95)])),
    ("man_b90_linear",     "extreme late blade: T=0 until 90%, straight to 0.95",         pw([(0,0),(0.9,0),(1,0.95)])),
    ("man_b75_concave",    "late blade, concave: 0.75 at 87.5%",                          pw([(0,0),(0.75,0),(0.875,0.75),(1,0.95)])),
    ("man_b50_end80",      "blade to 50%, straight to T_end = 0.80",                      pw([(0,0),(0.5,0),(1,0.80)])),
    ("man_b50_end90",      "blade to 50%, straight to T_end = 0.90",                      pw([(0,0),(0.5,0),(1,0.90)])),
    ("man_b25_end100",     "blade to 25%, straight to T_end = 1.0 exactly",               pw([(0,0),(0.25,0),(1,1.0)])),
    ("man_b50_overshoot",  "blade to 50%, overshoot to 1.0 at 70%, settle at 0.90",       pw([(0,0),(0.5,0),(0.7,1.0),(1,0.90)])),
    ("man_b25_dip",        "blade to 25%, rise to 0.6, dip to 0.2 at 65%, rise to 0.95",  pw([(0,0),(0.25,0),(0.5,0.6),(0.65,0.2),(1,0.95)])),
    ("man_noblade_030",    "no blade: start at T=0.3, straight to 0.95",                  pw([(0,0.3),(1,0.95)])),
    ("man_b10_plateau50",  "short blade to 10%, plateau at 0.5 from 30% to 70%, then 0.95", pw([(0,0),(0.1,0),(0.3,0.5),(0.7,0.5),(1,0.95)])),
]
# 4-D space-filling grid (2026-09-14), generated by grid_design.py (seed 20260914):
# b in [0,0.9], bend position r in [0.1,0.9] of the way from b to the end, bend height y in [0,1],
# T_end in [0.8,1.0]. Farthest-point order, so every prefix is a uniform cover:
# stage 1 = picks 1-16, stage 2 = 17-32, stage 3 = 33-64. Near-duplicate curves were skipped.
GRID = [   # name, stage, note, schedule
    ('man_g01_b90_r10_y100_T080', 1, '4-D grid stage 1 pick 1: T=0 until 90%, bend to 1.00 at 91.0% of training, end at 0.80', pw([(0.0, 0.0), (0.9, 0.0), (0.91, 1.0), (1.0, 0.8)])),
    ('man_g02_b00_r10_y100_T080', 1, '4-D grid stage 1 pick 2: no T=0 stretch, bend to 1.00 at 10.0% of training, end at 0.80', pw([(0.0, 0.0), (0.1, 1.0), (1.0, 0.8)])),
    ('man_g03_b00_r10_y100_T100', 1, '4-D grid stage 1 pick 3: no T=0 stretch, bend to 1.00 at 10.0% of training, end at 1.00', pw([(0.0, 0.0), (0.1, 1.0), (1.0, 1.0)])),
    ('man_g04_b74_r90_y004_T090', 1, '4-D grid stage 1 pick 4: T=0 until 74%, bend to 0.04 at 97.4% of training, end at 0.90', pw([(0.0, 0.0), (0.74, 0.0), (0.974, 0.04), (1.0, 0.9)])),
    ('man_g05_b02_r16_y097_T088', 1, '4-D grid stage 1 pick 5: T=0 until 2%, bend to 0.97 at 17.7% of training, end at 0.88', pw([(0.0, 0.0), (0.02, 0.0), (0.1768, 0.97), (1.0, 0.88)])),
    ('man_g06_b87_r46_y099_T096', 1, '4-D grid stage 1 pick 6: T=0 until 87%, bend to 0.99 at 93.0% of training, end at 0.96', pw([(0.0, 0.0), (0.87, 0.0), (0.9298, 0.99), (1.0, 0.96)])),
    ('man_g07_b35_r14_y092_T080', 1, '4-D grid stage 1 pick 7: T=0 until 35%, bend to 0.92 at 44.1% of training, end at 0.80', pw([(0.0, 0.0), (0.35, 0.0), (0.441, 0.92), (1.0, 0.8)])),
    ('man_g08_b42_r11_y098_T100', 1, '4-D grid stage 1 pick 8: T=0 until 42%, bend to 0.98 at 48.4% of training, end at 1.00', pw([(0.0, 0.0), (0.42, 0.0), (0.4838, 0.98), (1.0, 1.0)])),
    ('man_g09_b60_r17_y098_T085', 1, '4-D grid stage 1 pick 9: T=0 until 60%, bend to 0.98 at 66.8% of training, end at 0.85', pw([(0.0, 0.0), (0.6, 0.0), (0.668, 0.98), (1.0, 0.85)])),
    ('man_g10_b01_r12_y066_T080', 1, '4-D grid stage 1 pick 10: T=0 until 1%, bend to 0.66 at 12.9% of training, end at 0.80', pw([(0.0, 0.0), (0.01, 0.0), (0.1288, 0.66), (1.0, 0.8)])),
    ('man_g11_b04_r35_y098_T096', 1, '4-D grid stage 1 pick 11: T=0 until 4%, bend to 0.98 at 37.6% of training, end at 0.96', pw([(0.0, 0.0), (0.04, 0.0), (0.376, 0.98), (1.0, 0.96)])),
    ('man_g12_b01_r89_y026_T084', 1, '4-D grid stage 1 pick 12: T=0 until 1%, bend to 0.26 at 89.1% of training, end at 0.84', pw([(0.0, 0.0), (0.01, 0.0), (0.8911, 0.26), (1.0, 0.84)])),
    ('man_g13_b27_r12_y071_T085', 1, '4-D grid stage 1 pick 13: T=0 until 27%, bend to 0.71 at 35.8% of training, end at 0.85', pw([(0.0, 0.0), (0.27, 0.0), (0.3576, 0.71), (1.0, 0.85)])),
    ('man_g14_b07_r39_y100_T086', 1, '4-D grid stage 1 pick 14: T=0 until 7%, bend to 1.00 at 43.3% of training, end at 0.86', pw([(0.0, 0.0), (0.07, 0.0), (0.4327, 1.0), (1.0, 0.86)])),
    ('man_g15_b90_r21_y001_T098', 1, '4-D grid stage 1 pick 15: T=0 until 90%, bend to 0.01 at 92.1% of training, end at 0.98', pw([(0.0, 0.0), (0.9, 0.0), (0.921, 0.01), (1.0, 0.98)])),
    ('man_g16_b89_r11_y054_T085', 1, '4-D grid stage 1 pick 16: T=0 until 89%, bend to 0.54 at 90.2% of training, end at 0.85', pw([(0.0, 0.0), (0.89, 0.0), (0.9021, 0.54), (1.0, 0.85)])),
    ('man_g17_b34_r34_y099_T097', 2, '4-D grid stage 2 pick 17: T=0 until 34%, bend to 0.99 at 56.4% of training, end at 0.97', pw([(0.0, 0.0), (0.34, 0.0), (0.5644, 0.99), (1.0, 0.97)])),
    ('man_g18_b18_r12_y099_T095', 2, '4-D grid stage 2 pick 18: T=0 until 18%, bend to 0.99 at 27.8% of training, end at 0.95', pw([(0.0, 0.0), (0.18, 0.0), (0.2784, 0.99), (1.0, 0.95)])),
    ('man_g19_b74_r10_y066_T092', 2, '4-D grid stage 2 pick 19: T=0 until 74%, bend to 0.66 at 76.6% of training, end at 0.92', pw([(0.0, 0.0), (0.74, 0.0), (0.766, 0.66), (1.0, 0.92)])),
    ('man_g20_b49_r20_y069_T080', 2, '4-D grid stage 2 pick 20: T=0 until 49%, bend to 0.69 at 59.2% of training, end at 0.80', pw([(0.0, 0.0), (0.49, 0.0), (0.592, 0.69), (1.0, 0.8)])),
    ('man_g21_b01_r14_y062_T093', 2, '4-D grid stage 2 pick 21: T=0 until 1%, bend to 0.62 at 14.9% of training, end at 0.93', pw([(0.0, 0.0), (0.01, 0.0), (0.1486, 0.62), (1.0, 0.93)])),
    ('man_g22_b69_r90_y040_T098', 2, '4-D grid stage 2 pick 22: T=0 until 69%, bend to 0.40 at 96.9% of training, end at 0.98', pw([(0.0, 0.0), (0.69, 0.0), (0.969, 0.4), (1.0, 0.98)])),
    ('man_g23_b17_r43_y098_T099', 2, '4-D grid stage 2 pick 23: T=0 until 17%, bend to 0.98 at 52.7% of training, end at 0.99', pw([(0.0, 0.0), (0.17, 0.0), (0.5269, 0.98), (1.0, 0.99)])),
    ('man_g24_b12_r88_y047_T099', 2, '4-D grid stage 2 pick 24: T=0 until 12%, bend to 0.47 at 89.4% of training, end at 0.99', pw([(0.0, 0.0), (0.12, 0.0), (0.8944, 0.47), (1.0, 0.99)])),
    ('man_g25_b03_r57_y095_T100', 2, '4-D grid stage 2 pick 25: T=0 until 3%, bend to 0.95 at 58.3% of training, end at 1.00', pw([(0.0, 0.0), (0.03, 0.0), (0.5829, 0.95), (1.0, 1.0)])),
    ('man_g26_b04_r29_y073_T094', 2, '4-D grid stage 2 pick 26: T=0 until 4%, bend to 0.73 at 31.8% of training, end at 0.94', pw([(0.0, 0.0), (0.04, 0.0), (0.3184, 0.73), (1.0, 0.94)])),
    ('man_g27_b00_r90_y100_T080', 2, '4-D grid stage 2 pick 27: no T=0 stretch, bend to 1.00 at 90.0% of training, end at 0.80', pw([(0.0, 0.0), (0.9, 1.0), (1.0, 0.8)])),
    ('man_g28_b23_r34_y079_T080', 2, '4-D grid stage 2 pick 28: T=0 until 23%, bend to 0.79 at 49.2% of training, end at 0.80', pw([(0.0, 0.0), (0.23, 0.0), (0.4918, 0.79), (1.0, 0.8)])),
    ('man_g29_b72_r33_y099_T099', 2, '4-D grid stage 2 pick 29: T=0 until 72%, bend to 0.99 at 81.2% of training, end at 0.99', pw([(0.0, 0.0), (0.72, 0.0), (0.8124, 0.99), (1.0, 0.99)])),
    ('man_g30_b29_r10_y053_T082', 2, '4-D grid stage 2 pick 30: T=0 until 29%, bend to 0.53 at 36.1% of training, end at 0.82', pw([(0.0, 0.0), (0.29, 0.0), (0.361, 0.53), (1.0, 0.82)])),
    ('man_g31_b47_r40_y100_T087', 2, '4-D grid stage 2 pick 31: T=0 until 47%, bend to 1.00 at 68.2% of training, end at 0.87', pw([(0.0, 0.0), (0.47, 0.0), (0.682, 1.0), (1.0, 0.87)])),
    ('man_g32_b70_r60_y097_T098', 2, '4-D grid stage 2 pick 32: T=0 until 70%, bend to 0.97 at 88.0% of training, end at 0.98', pw([(0.0, 0.0), (0.7, 0.0), (0.88, 0.97), (1.0, 0.98)])),
    ('man_g33_b35_r53_y096_T099', 3, '4-D grid stage 3 pick 33: T=0 until 35%, bend to 0.96 at 69.5% of training, end at 0.99', pw([(0.0, 0.0), (0.35, 0.0), (0.6945, 0.96), (1.0, 0.99)])),
    ('man_g34_b23_r17_y099_T084', 3, '4-D grid stage 3 pick 34: T=0 until 23%, bend to 0.99 at 36.1% of training, end at 0.84', pw([(0.0, 0.0), (0.23, 0.0), (0.3609, 0.99), (1.0, 0.84)])),
    ('man_g35_b26_r18_y082_T100', 3, '4-D grid stage 3 pick 35: T=0 until 26%, bend to 0.82 at 39.3% of training, end at 1.00', pw([(0.0, 0.0), (0.26, 0.0), (0.3932, 0.82), (1.0, 1.0)])),
    ('man_g36_b04_r14_y042_T081', 3, '4-D grid stage 3 pick 36: T=0 until 4%, bend to 0.42 at 17.4% of training, end at 0.81', pw([(0.0, 0.0), (0.04, 0.0), (0.1744, 0.42), (1.0, 0.81)])),
    ('man_g37_b37_r12_y077_T097', 3, '4-D grid stage 3 pick 37: T=0 until 37%, bend to 0.77 at 44.6% of training, end at 0.97', pw([(0.0, 0.0), (0.37, 0.0), (0.4456, 0.77), (1.0, 0.97)])),
    ('man_g38_b69_r10_y077_T099', 3, '4-D grid stage 3 pick 38: T=0 until 69%, bend to 0.77 at 72.1% of training, end at 0.99', pw([(0.0, 0.0), (0.69, 0.0), (0.721, 0.77), (1.0, 0.99)])),
    ('man_g39_b72_r18_y095_T089', 3, '4-D grid stage 3 pick 39: T=0 until 72%, bend to 0.95 at 77.0% of training, end at 0.89', pw([(0.0, 0.0), (0.72, 0.0), (0.7704, 0.95), (1.0, 0.89)])),
    ('man_g40_b10_r10_y060_T083', 3, '4-D grid stage 3 pick 40: T=0 until 10%, bend to 0.60 at 19.0% of training, end at 0.83', pw([(0.0, 0.0), (0.1, 0.0), (0.19, 0.6), (1.0, 0.83)])),
    ('man_g41_b56_r23_y093_T080', 3, '4-D grid stage 3 pick 41: T=0 until 56%, bend to 0.93 at 66.1% of training, end at 0.80', pw([(0.0, 0.0), (0.56, 0.0), (0.6612, 0.93), (1.0, 0.8)])),
    ('man_g42_b64_r41_y003_T080', 3, '4-D grid stage 3 pick 42: T=0 until 64%, bend to 0.03 at 78.8% of training, end at 0.80', pw([(0.0, 0.0), (0.64, 0.0), (0.7876, 0.03), (1.0, 0.8)])),
    ('man_g43_b09_r12_y049_T100', 3, '4-D grid stage 3 pick 43: T=0 until 9%, bend to 0.49 at 19.9% of training, end at 1.00', pw([(0.0, 0.0), (0.09, 0.0), (0.1992, 0.49), (1.0, 1.0)])),
    ('man_g44_b11_r11_y087_T082', 3, '4-D grid stage 3 pick 44: T=0 until 11%, bend to 0.87 at 20.8% of training, end at 0.82', pw([(0.0, 0.0), (0.11, 0.0), (0.2079, 0.87), (1.0, 0.82)])),
    ('man_g45_b56_r11_y100_T092', 3, '4-D grid stage 3 pick 45: T=0 until 56%, bend to 1.00 at 60.8% of training, end at 0.92', pw([(0.0, 0.0), (0.56, 0.0), (0.6084, 1.0), (1.0, 0.92)])),
    ('man_g46_b35_r46_y095_T081', 3, '4-D grid stage 3 pick 46: T=0 until 35%, bend to 0.95 at 64.9% of training, end at 0.81', pw([(0.0, 0.0), (0.35, 0.0), (0.649, 0.95), (1.0, 0.81)])),
    ('man_g47_b37_r88_y040_T096', 3, '4-D grid stage 3 pick 47: T=0 until 37%, bend to 0.40 at 92.4% of training, end at 0.96', pw([(0.0, 0.0), (0.37, 0.0), (0.9244, 0.4), (1.0, 0.96)])),
    ('man_g48_b85_r13_y089_T097', 3, '4-D grid stage 3 pick 48: T=0 until 85%, bend to 0.89 at 87.0% of training, end at 0.97', pw([(0.0, 0.0), (0.85, 0.0), (0.8695, 0.89), (1.0, 0.97)])),
    ('man_g49_b67_r27_y098_T083', 3, '4-D grid stage 3 pick 49: T=0 until 67%, bend to 0.98 at 75.9% of training, end at 0.83', pw([(0.0, 0.0), (0.67, 0.0), (0.7591, 0.98), (1.0, 0.83)])),
    ('man_g50_b60_r11_y065_T084', 3, '4-D grid stage 3 pick 50: T=0 until 60%, bend to 0.65 at 64.4% of training, end at 0.84', pw([(0.0, 0.0), (0.6, 0.0), (0.644, 0.65), (1.0, 0.84)])),
    ('man_g51_b64_r11_y050_T097', 3, '4-D grid stage 3 pick 51: T=0 until 64%, bend to 0.50 at 68.0% of training, end at 0.97', pw([(0.0, 0.0), (0.64, 0.0), (0.6796, 0.5), (1.0, 0.97)])),
    ('man_g52_b32_r15_y064_T095', 3, '4-D grid stage 3 pick 52: T=0 until 32%, bend to 0.64 at 42.2% of training, end at 0.95', pw([(0.0, 0.0), (0.32, 0.0), (0.422, 0.64), (1.0, 0.95)])),
    ('man_g53_b24_r23_y096_T098', 3, '4-D grid stage 3 pick 53: T=0 until 24%, bend to 0.96 at 41.5% of training, end at 0.98', pw([(0.0, 0.0), (0.24, 0.0), (0.4148, 0.96), (1.0, 0.98)])),
    ('man_g54_b38_r12_y051_T098', 3, '4-D grid stage 3 pick 54: T=0 until 38%, bend to 0.51 at 45.4% of training, end at 0.98', pw([(0.0, 0.0), (0.38, 0.0), (0.4544, 0.51), (1.0, 0.98)])),
    ('man_g55_b67_r86_y094_T082', 3, '4-D grid stage 3 pick 55: T=0 until 67%, bend to 0.94 at 95.4% of training, end at 0.82', pw([(0.0, 0.0), (0.67, 0.0), (0.9538, 0.94), (1.0, 0.82)])),
    ('man_g56_b24_r13_y086_T097', 3, '4-D grid stage 3 pick 56: T=0 until 24%, bend to 0.86 at 33.9% of training, end at 0.97', pw([(0.0, 0.0), (0.24, 0.0), (0.3388, 0.86), (1.0, 0.97)])),
    ('man_g57_b01_r59_y087_T083', 3, '4-D grid stage 3 pick 57: T=0 until 1%, bend to 0.87 at 59.4% of training, end at 0.83', pw([(0.0, 0.0), (0.01, 0.0), (0.5941, 0.87), (1.0, 0.83)])),
    ('man_g58_b86_r13_y065_T099', 3, '4-D grid stage 3 pick 58: T=0 until 86%, bend to 0.65 at 87.8% of training, end at 0.99', pw([(0.0, 0.0), (0.86, 0.0), (0.8782, 0.65), (1.0, 0.99)])),
    ('man_g59_b55_r44_y098_T097', 3, '4-D grid stage 3 pick 59: T=0 until 55%, bend to 0.98 at 74.8% of training, end at 0.97', pw([(0.0, 0.0), (0.55, 0.0), (0.748, 0.98), (1.0, 0.97)])),
    ('man_g60_b37_r24_y083_T085', 3, '4-D grid stage 3 pick 60: T=0 until 37%, bend to 0.83 at 52.1% of training, end at 0.85', pw([(0.0, 0.0), (0.37, 0.0), (0.5212, 0.83), (1.0, 0.85)])),
    ('man_g61_b06_r44_y095_T080', 3, '4-D grid stage 3 pick 61: T=0 until 6%, bend to 0.95 at 47.4% of training, end at 0.80', pw([(0.0, 0.0), (0.06, 0.0), (0.4736, 0.95), (1.0, 0.8)])),
    ('man_g62_b06_r15_y071_T100', 3, '4-D grid stage 3 pick 62: T=0 until 6%, bend to 0.71 at 20.1% of training, end at 1.00', pw([(0.0, 0.0), (0.06, 0.0), (0.201, 0.71), (1.0, 1.0)])),
    ('man_g63_b01_r89_y065_T100', 3, '4-D grid stage 3 pick 63: T=0 until 1%, bend to 0.65 at 89.1% of training, end at 1.00', pw([(0.0, 0.0), (0.01, 0.0), (0.8911, 0.65), (1.0, 1.0)])),
    ('man_g64_b02_r62_y084_T098', 3, '4-D grid stage 3 pick 64: T=0 until 2%, bend to 0.84 at 62.8% of training, end at 0.98', pw([(0.0, 0.0), (0.02, 0.0), (0.6276, 0.84), (1.0, 0.98)])),
]
RUNS = ([{"name": n, "note": note, "schedule": s, "phase": PHASE} for n, note, s in ROUND1 + ROUND2]
        + [{"name": n, "note": note, "schedule": s, "phase": "grid", "stage": st} for n, st, note, s in GRID])

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--manifest", default=MANIFEST); ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    existing = json.load(open(a.manifest)) if os.path.exists(a.manifest) else {"runs": []}
    names = {r["name"] for r in RUNS}
    merged = dict(existing); merged["runs"] = [e for e in existing.get("runs", []) if e.get("name") not in names] + RUNS
    for r in RUNS: print(f"  {r['phase']:<6} {r['name']:<30} {r['schedule']['control_points']}")
    if a.dry_run: return
    if os.path.exists(a.manifest): shutil.copy2(a.manifest, a.manifest + ".bak")
    json.dump(merged, open(a.manifest, "w"), indent=2); print(f"wrote {a.manifest} ({len(merged['runs'])} runs)")

if __name__ == "__main__":
    main()
